swipe:
  3:
    up:
      command: "xdotool key ctrl+alt+Down"
    down:
      command: "xdotool key ctrl+alt+Up"
  4:
    up:
      command: "xdotool key super"
    down:
      command: "xdotool key super"
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
